server:
  servlet:
    context-path: /zh
spring:
  profiles:
    active: dev
  #指定项目静态资源路径
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.upload-path}
  #session 相关配置
  session:
    timeout: 3600
    redis:
      namespace: zh-session
#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zh.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)",   UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #数据库是否开启大写命名
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    #关闭banner打印
    banner: false
    #是否缓存 Sql 解析，默认不缓存
    sql-parser-cache: true
  # 原生配置
  configuration:
    #是否开启自动驼峰命名规则
    map-underscore-to-camel-case: true
#    cache-enabled: false
#security
security:
  web:
    ignore:
      - /swagger-ui.html
      - /webjars/**
      - /v2/**
      - /swagger-resources/**
      - /**/*.*
      - /login
      - /logout
      - /authentication/check
      - /verification/code
      - ${websocket.endpoint.path}/**
    loginProcessingUrl: /authentication/login
    logoutUrl: /authentication/logout
    #权限表达式
    access: '@permissionService.hasPermission(request,authentication)'
  session:
    #允许登陆限制人数
    maximumSessions: 10
    #不允许重复登陆
    notAllowLogin: false
    #记住我时间 单位：s 默认 14天
    #remember_time: 60
  #验证码登陆配置
  #code:
    #验证码长度 默认4位
    #length: 4
    #过期时间（单位：s） 默认2分钟
    #expiredTime: 120

#websocket
websocket:
  endpoint:
    path: /websocket
#在线预览服务访问路径 外网访问
onlinePreview:
  url: http://187.129.177.218:8012/onlinePreview?url=http://{}:{}{}{}

#忽略swagger异常
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
#气象预警
meteorological:
  warning:
    url: http://www.weather.com.cn/data/alarm_xml/alarminfo.xml