#自定义的属性，指定了一个路径，注意要以/结尾
file:
  upload-path: D:/upload/
server:
  port: 10086
spring:
  application:
    name: zh-dev
  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  kafka:
    bootstrap-servers: 192.168.16.27:9092
#  datasource:
#    dynamic:
#      #本地环境开启p6spy显示sql语句
#      p6spy: true
#      primary: sqlserver
#      datasource:
#        #单纯多数据源配置 可配置多个
#        sqlserver:
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://localhost;DatabaseName=master
#          username: sa
#          password: 123456
#          hikari:
#            minimum-idle: 15
#            maximum-pool-size: 15
#            auto-commit: true
#            idle-timeout: 600000
#            max-lifetime: 1800000
#            connection-timeout: 30000
  datasource:
    dynamic:
      #本地环境开启p6spy显示sql语句
      p6spy: true
      primary: mysql
      datasource:
        #单纯多数据源配置 可配置多个
        mysql:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost/homework?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=CTT
          username: root
          password: root
          hikari:
            minimum-idle: 15
            maximum-pool-size: 15
            auto-commit: true
            idle-timeout: 600000
            max-lifetime: 1800000
            connection-timeout: 30000
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 30001
    database: 3
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
    password: warter@2018!^&


#开发环境开启swagger
swagger:
  enable: true
